default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: to_do_db_development

test:
  <<: *default
  database: to_do_db_test

production:
  <<: *default
  database: to_do_db_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

